"""add language to posts

Revision ID: 18abeb897af0
Revises: 53c072ce568d
Create Date: 2021-06-15 11:06:17.020670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18abeb897af0'
down_revision = '53c072ce568d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
